// @prompt externalService

// @name AccessToken
GET https://{{externalService}}/Auth/AccessToken

###

// @prompt externalService
POST https://{{externalService}}/WeatherData/ByLocation
Authorization: Bearer {{AccessToken.response.body.$.accessToken}}
content-type: application/json

{
  "locations": [
    {
      "city": "Romulus",
      "state": "MI",
      "zip": "48174"
    },
    {
      "city": "Dearborn",
      "state": "MI",
      "zip": "48124"
    }
  ]
}


###

POST http://localhost:5046/weatherforecast/
content-type: application/json

{
  "locations": [
    {
      "id": "rm48174",
      "city": "Romuluss",
      "state": "MI",
      "zip": "48174"
    },
    {
      "id": "dmi48124",
      "city": "Dearborn",
      "state": "MI",
      "zip": "48124"
    }
  ]
}
